version: '3'
services:
  p-broadcast:
    build: 
      context: ./p-broadcast
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./p-broadcast:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BROWSER=none